services:

  app:
    build: .
    # we let the container up indefinitely
    command: tail -f /dev/null
    develop:
        watch:
          - action: sync
            path: ./app.py
            target: /app/app.py
          - action: rebuild
            path: requirements.txt