
version: "3.7"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - backend:/usr/src/app
    ports:
      - "3000:3000"
    env_file: 
      - .env
    depends_on: 
      - database

  database:
    image: "postgres:14.5"
    volumes: 
      - database:/var/lib/postgresql/data
    env_file: 
      - .env

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/usr/src/app
    ports:
      - "3001:3001"
    depends_on: 
      - backend
